spring.application.name=db-react-springboot-be

spring.datasource.url=jdbc:postgresql://localhost:5432/db_react_springboot
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.open-in-view=false

server.port=8081

# MetaSync auto-polling
metasync.polling.enabled=true
metasync.polling.cron=*/30 * * * * *
